accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('login/', views.CustomUserLoginView.as_view(), name='login'),
    path('logout/', views.CustomUserLogoutView.as_view(), name='logout'),
    path('activation/<int:pk>', views.UserActivationView.as_view(), name='activation'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('products.urls')),
    path('', include('customers.urls')),
    path('', include('orders.urls')),
    path('api/', include('orders.api.urls_api')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customers/urls.py
from django.urls import path
from . import views

app_name = 'customers'

urlpatterns = [
    path('edit-profile/', views.EditProfileView.as_view(), name='edit-profile'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('change-password/', views.CustomPasswordChangeView.as_view(), name='change-password'),
    path('new-address/', views.AddNewAddressView.as_view(), name='new-address'),
    path('address/', views.ShowAddressView.as_view(), name='address'),
    path('address/<int:pk>/delete/', views.DeleteAddressView.as_view(), name='delete-address'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'


urlpatterns = [
    path('add-product/', views.AddToOrderItem.as_view(), name='add-product'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('paid-orders/', views.PaidOrdersView.as_view(), name='paid-orders'),
    path('order/<int:pk>/', views.OrderDetailsView.as_view(), name='order-details'),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('products/<slug:slug>/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('', views.HomePageView.as_view(), name='home'),
    path('category/<slug:slug>/<int:pk>/', views.CategoryProductView.as_view(), name='category_products')
]

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
</head>
<body style=" {% block body_style %} {% endblock %} ">
{% include 'base/navbar.html' %}

<div class="pt-12">

    {% block content %} {% endblock %}
</div>
</body>
</html>

templates/base/navbar.html
<nav class="bg-gray-600 p-4 opacity-90 fixed w-full z-10 top-0 flex flex-col">
    <div class="container mx-auto flex justify-between items-center">
        <div>
            <ul class="flex space-x-4 items-center">
                <li>
                    {% if logged_in_user %}
                        <a href="{% url 'customers:profile' %}"
                           class="text-white flex items-center font-bold hover:text-red-500">
                            <span>{{ logged_in_user }}</span> <!-- Name to the right -->
                        </a>
                    {% endif %}
                </li>
                <li><a href="{% url 'products:home' %}" class="text-white hover:text-red-500">Categories</a></li>
                <li>
                    <form id="card" method="get"
                          action="{% if logged_in_user %} {% url 'orders:cart' %} {% else %} {% url 'accounts:login' %} {% endif %}">
                        <!-- Use Django template variable to set the cookie -->
                        <button type="submit" id="cardButton"
                                class="text-white hover:text-red-500">
                            🛒Card
                        </button>
                    </form>
                </li>
            </ul>
        </div>
        <div>
            {% if logged_in_user %}
                <a href="{% url 'accounts:logout' %}" class="text-white text-xl font-bold hover:text-red-500">Logout</a>
            {% else %}
                <div class="flex ">
                    <form id="loginForm" method="get" action="{% url 'accounts:login' %}">
                        <!-- Use Django template variable to set the cookie -->
                        <button type="submit" id="loginButton2"
                                class="text-white text-xl font-bold pr-2 pb-2 hover:text-red-500 px-2">
                            Login
                        </button>
                    </form>

                    <form id="signupForm" method="get" action="{% url 'accounts:signup' %}">
                        <!-- Use Django template variable to set the cookie -->
                        <button type="submit" id="signupButton"
                                class="text-white text-xl font-bold pr-2 pb-2 hover:text-red-500 px-2">
                            Signup
                        </button>
                    </form>
                </div>

            {% endif %}
        </div>
    </div>
    <div id="messages"></div>


    <script>
        document.getElementById("loginButton2").addEventListener("click", function () {
            // Get the current_url value
            var currentUrl = "{{ current_url }}";

            // Check if the current URL contains any of the keywords
            if (currentUrl.indexOf('login') === -1 && currentUrl.indexOf('signup') === -1 && currentUrl.indexOf('activation') === -1) {
                // Set the cookie
                document.cookie = "next_url=" + currentUrl + ";path=/";
            }
        });
    </script>


    <script>
        document.getElementById("signupButton").addEventListener("click", function () {
            // Get the value you want to save in the cookie
            var currentUrl = "{{ current_url }}";

            // Check if the current URL contains any of the keywords
            if (currentUrl.indexOf('login') === -1 && currentUrl.indexOf('signup') === -1 && currentUrl.indexOf('activation') === -1) {
                // Set the cookie
                document.cookie = "next_url=" + currentUrl + ";path=/";
            }
        });
    </script>

    <script>
        {% if not logged_in_user %}
            document.getElementById("cardButton").addEventListener("click", function () {
                // Get the current_url value
                var currentUrl = "http://127.0.0.1:8000/en/cart/";

                // Check if the current URL contains any of the keywords
                if (currentUrl.indexOf('login') === -1 && currentUrl.indexOf('signup') === -1 && currentUrl.indexOf('activation') === -1) {
                    // Set the cookie
                    document.cookie = "next_url=" + currentUrl + ";path=/";
                }
            });
        {% endif %}
    </script>
</nav>