config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('products.urls')),
    path('', include('customers.urls')),
    path('', include('orders.urls')),
    path('api/', include('orders.api.urls_api')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'


urlpatterns = [
    path('add-product/', views.AddToOrderItem.as_view(), name='add-product'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('paid-orders/', views.PaidOrdersView.as_view(), name='paid-orders'),
    path('order/<int:pk>/', views.OrderDetailsView.as_view(), name='order-details'),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('products/<slug:slug>/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('', views.HomePageView.as_view(), name='home'),
    path('category/<slug:slug>/<int:pk>/', views.CategoryProductView.as_view(), name='category_products')
]

products/models.py
from django.core.validators import MinValueValidator
from django.db import models
from django.core.exceptions import ValidationError
from core.models import TimeStampMixin, LogicalMixin
from utils.filepath import get_image_upload_path
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class Product(LogicalMixin, TimeStampMixin):
    name = models.CharField(verbose_name=_("Name"), max_length=200)
    brand = models.CharField(verbose_name=_("Brand"), max_length=200, null=True, blank=True)
    description = models.TextField(verbose_name=_("Description"), null=True, blank=True)
    stock = models.PositiveIntegerField(verbose_name=_("Stock"), )
    categories = models.ManyToManyField('Category', verbose_name=_("Categories"), related_name='products')
    slug = models.SlugField(verbose_name=_("Slug"), null=True, blank=True)

    def clean(self):
        super().clean()
        self.slug = self.name

    class Meta:
        verbose_name = _("Product")
        verbose_name_plural = _("Products")

    def __str__(self):
        return f'{self.name} - stock={self.stock}'

    def product_details(self):
        temp = dict()
        temp['product_id'] = self.id
        temp['name'] = self.name
        temp['brand'] = self.brand
        temp['description'] = self.description
        temp['stock'] = self.stock
        temp['categories'] = self.categories.all()
        temp['price'] = self.product_price()
        temp['final_price'] = self.final_price()
        temp['images'] = self.get_images()
        temp['discount_amount'] = self.get_discount()[0]
        temp['discount_type'] = self.get_discount()[1]
        return temp

    def get_discount(self):
        discount = self.discounts.filter(is_deleted=False).first()
        if discount and discount.expiration_date >= timezone.now().date():
            if discount.is_percent_type:
                return discount.amount, '%'
            else:
                return discount.amount, '$'
        return None, None

    def product_price(self):
        return self.prices.get(is_deleted=False).price

    def final_price(self):
        discount = self.discounts.filter(is_deleted=False).first()
        if discount is None or discount.expiration_date < timezone.now().date():
            return round(self.product_price(), 2)
        if discount.is_percent_type:
            return round(self.product_price() * (1 - discount.amount / 100), 2)
        return round(self.product_price() - discount.amount, 2)

    def get_images(self):
        images = self.images.all()
        return images

    @property
    def get_first_image(self):
        return self.get_images().first()


class Price(LogicalMixin, TimeStampMixin):
    updated_at = None
    product = models.ForeignKey(Product,
                                verbose_name=_("Product"),
                                on_delete=models.SET_NULL, null=True,
                                related_name='prices')
    price = models.DecimalField(verbose_name=_("Price"), max_digits=15, decimal_places=2)

    def price_after_discount(self):
        if self.product.discounts.first():
            if self.product.discounts.first().is_percent_type:
                return round(self.price * (1 - (self.product.discounts.first().amount / 100)), 2)
            else:
                return (
                    round(self.price - self.product.discounts.first().amount, 2)
                    if (self.price - self.product.discounts.first().amount) > 0
                    else 0
                )
        return round(self.price, 2)

    def discount_amount(self):
        return self.price - self.price_after_discount()

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['product'],
                condition=models.Q(is_deleted=False),
                name='Product can have just 1 price'
            )
        ]
        verbose_name = _("Price")
        verbose_name_plural = _("Prices")

    def __str__(self):
        return f'{self.product.name} - price={self.price}'


class Image(LogicalMixin, TimeStampMixin):
    product = models.ForeignKey(Product,
                                verbose_name=_("Product"),
                                on_delete=models.CASCADE,
                                related_name='images')
    image = models.ImageField(verbose_name=_("Image"),
                              upload_to=get_image_upload_path
                              )

    def __str__(self):
        return f'{self.product.brand}-{self.product.name}'

    class Meta:
        verbose_name = _('Image')
        verbose_name_plural = _('Images')


class Category(LogicalMixin, TimeStampMixin):
    category = models.CharField(verbose_name=_("Category"), max_length=200)
    parent = models.ForeignKey('self',
                               verbose_name=_("Parent"),
                               on_delete=models.SET_NULL,
                               null=True, blank=True,
                               related_name='child_categories')
    slug = models.SlugField(verbose_name=_("Slug"), null=True, blank=True)

    def clean(self):
        super().clean()
        self.slug = self.category
        if self.parent:
            if self.parent == self:
                raise ValidationError("Parent category cannot be itself.")
            if self.parent.parent == self:
                raise ValidationError("Child category cannot be the parent of its parent.")

    def __str__(self):
        if self.parent:
            return f'{self.category} - parent: {self.parent.category}'
        return f'{self.category}'

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")


class Discount(LogicalMixin, TimeStampMixin):
    product = models.ForeignKey(Product, verbose_name=_("Product"), on_delete=models.CASCADE, related_name='discounts')
    is_percent_type = models.BooleanField(verbose_name=_("Is percent type"), default=True)
    amount = models.DecimalField(verbose_name=_("Amount"),
                                 max_digits=15, decimal_places=2,
                                 validators=[MinValueValidator(0.1)])
    expiration_date = models.DateField(verbose_name=_("Expiration date"), )

    class Meta:
        constraints = [
            models.CheckConstraint(
                check=models.Q(is_percent_type=False) | models.Q(amount__lte=100),
                name='percent_type_constraint'
            ),
            models.UniqueConstraint(
                fields=['product'],
                condition=models.Q(is_deleted=False),
                name='Product can have just 1 discount'
            )
        ]
        verbose_name = _("Discount")
        verbose_name_plural = _("Discounts")

    def __str__(self):
        if self.is_percent_type:
            return f'{self.product.name} - {self.amount}%'
        return f'{self.product.name} - {self.amount}$'

products/views.py
from django.views.generic import DetailView, TemplateView
from products.models import Product, Category
from django.shortcuts import get_object_or_404, redirect
from core.mixin import NavbarMixin


class ProductDetailView(NavbarMixin, DetailView):
    model = Product
    template_name = 'product.html'

    def dispatch(self, request, *args, **kwargs):
        self.product = get_object_or_404(Product, pk=self.kwargs.get('pk'), slug=self.kwargs.get('slug'),
                                         is_active=True)

        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product'] = self.product.product_details()
        return context


class HomePageView(NavbarMixin, TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        categories = Category.objects.all()
        context['categories'] = dict()
        for category in categories:
            context['categories'][category.id] = {
                'name': category.category,
                'products': category.products.filter(stock__gt=0, is_active=True).order_by('-created_at')
            }
        return context


class CategoryProductView(NavbarMixin, TemplateView):
    template_name = 'category_products.html'

    def dispatch(self, request, *args, **kwargs):
        self.category = get_object_or_404(Category, slug=self.kwargs.get('slug'), pk=self.kwargs.get('pk'))
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        available = self.category.products.filter(stock__gt=0, is_active=True).order_by('-created_at')
        unavailable = self.category.products.filter(stock__lte=0, is_active=True).order_by('-created_at')

        context['products'] = list(available) + list(unavailable)
        context['category'] = f"{self.kwargs.get('slug')}"
        context['children'] = self.category.child_categories.all()

        return context

#
# class TestView(APIView):
#     def get_queryset(self):
#         user = self.request.user
#         if self.request.method == "GET" and "view_order" in user.groups.values_list("permissions", flat=True):
#             return Order.objects.all()
#         if self.request.method == "GET" and "view_order_mine" in user.groups.values_list("permissions", flat=True):
#             return Order.objects.filter(customer=user)

products/templates/category_products.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}{{ product.brand }} {% endblock %}

{% block content %}

    <div class="flex flex-col items-center justify-center text-center ">
        <div class="flex flex-col items-center justify-center text-center mt-10 border rounded-md bg-gray-100"
             style="width: 95%">
            <h2 class="border-b-2 border-blue-500 mt-4 text-3xl font-bold">{{ category }}</h2>
            <div class="grid grid-cols-3 gap-4 mt-4">
                <!-- Loop through and generate divs -->
                {% for product in products %}
                    <div class="flex flex-col mx-2 border border-gray-300 p-4 rounded m-1 bg-blue-100 w-full"
                         style="width: 300px;">
                        <!-- Product name -->
                        <h3 class="text-lg font-semibold mb-2">{{ product.name }}</h3>
                        <!-- Product image -->
                        <div style="width: 100%; height: 200px; overflow: hidden;" class="rounded">
                            <a href="{% url 'products:product_detail' slug=product.slug pk=product.pk %}"><img
                                    src="{{ product.get_first_image.image.url }}" alt="image"
                                    style="width: 100%; height: 100%; object-fit: cover;"></a>
                        </div>
                        <div class="flex justify-around">
                            <p class="pr-4"{% if product.product_price != product.final_price %}
                               style="text-decoration: line-through;" {% else %}
                               style="display: none;" {% endif %}>{{ product.product_price }}</p>
                            <p class="pl-4">{{ product.final_price }}</p>
                        </div>
                        <!-- Add to Cart button -->
                        <form id="add-to-cart-form-{{ product.id }}" method="post"
                              action="{% url 'orders:add-product' %}"
                              onsubmit="addToCart(event, '{{ product.id }}')">
                            {% csrf_token %}
                            <input type="hidden" name="product_id" value="{{ product.id }}">
                            <div class="text-center mt-8">
                                <button type="submit"
                                        class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                                    Add to Cart
                                </button>
                            </div>
                        </form>
                        <!-- Product content goes here -->
                    </div>
                {% endfor %}
            </div>

        </div>
        {% if children %}
            <div class="flex flex-col items-center justify-center text-center mt-10 border rounded-md bg-gray-100"
                 style="width: 95%">
                <h2 class="border-b-2 border-blue-500 mt-4 text-3xl font-bold mb-8">Sub Categories</h2>
                <hr class="w-full border-gray-300 mb-4 ">

                {% for child_category in children %}
                    <div class="grid grid-cols-3 gap-4 mt-4">
                        <h3 class="border-b-2 border-blue-500 mt-4 text-2xl font-bold mb-8">
                            <a href="{% url 'products:category_products' slug=child_category.slug pk=child_category.pk %}">{{ child_category.category }}</a>
                        </h3>
                    </div>
                {% endfor %}
            </div>
        {% endif %}

    </div>
    <script>
        function addToCart(event, productId) {
            event.preventDefault(); // Prevent the default form submission behavior

            var form = document.getElementById("add-to-cart-form-" + productId);
            var formData = new FormData(form);

            fetch(form.action, {
                method: form.method,
                body: formData,
                headers: {
                    'X-Requested-With': 'XMLHttpRequest'
                }
            })
                .then(response => response.json())
                .then(data => {
                    // Handle the JSON response
                    var message = data.response; // Extract the message from the response
                    displayMessage(message); // Display the message
                })
                .catch(error => {
                    // Handle error here
                    console.error('Error:', error);
                    // Add error message
                    var errorMessage = 'Failed to add product to cart. Please try again.';
                    displayMessage(errorMessage); // Display the error message
                });
        }

        function displayMessage(message) {
            var messagesDiv = document.getElementById("messages");
            // Clear existing messages
            messagesDiv.innerHTML = '';

            var messageElement = document.createElement("div");
            messageElement.classList.add("alert");
            messageElement.textContent = message;
            messagesDiv.appendChild(messageElement);
        }
    </script>

{% endblock %}

products/templates/home.html
{% extends "base/base.html" %}
{% load static %}
{% block title %} Home {% endblock %}

{% block content %}
    <div class="flex flex-col justify-center items-center mx-auto w-10/12 mt-4 ">
        {% for id, category in categories.items %}
            <div class="flex flex-col justify-center items-center border border-gray-400 p-4 rounded m-1 mb-4 bg-gray-100"
                 style="width: 95%">
                <h2 class="text-xl font-semibold mb-4"><a
                        href="{% url 'products:category_products' slug=category.name pk=id %}">{{ category.name }}</a>
                </h2>
                <hr class="w-full border-gray-300 mb-4">
                <div class="flex items-center justify-around flex-wrap">
                    <!-- Loop through products in category -->
                    {% for product in category.products %}
                        {% if forloop.counter <= 4 %}
                            <div class="flex flex-col w-1/4 mx-2 border border-gray-300 p-4 rounded m-1 bg-blue-100"
                                 style="width: 225px;">
                                <!-- Product name -->
                                <h3 class="text-lg font-semibold mb-2">{{ product.name }}</h3>
                                <!-- Product image -->
                                <div style="width: 100%; height: 200px; overflow: hidden;" class="rounded">
                                    <a href="{% url 'products:product_detail' slug=product.name pk=product.pk %}"><img
                                            src="{{ product.get_first_image.image.url }}" alt="image"
                                            style="width: 100%; height: 100%; object-fit: cover;"></a>
                                </div>
                                <div class="flex justify-around">
                                    <p class="pr-4"{% if product.product_price != product.final_price %}
                                       style="text-decoration: line-through;" {% else %}
                                       style="display: none;" {% endif %}>{{ product.product_price }}</p>
                                    <p class="pl-4">{{ product.final_price }}</p>
                                </div>
                                <!-- Add to Cart button -->
                                <form id="add-to-cart-form-{{ product.id }}" method="post"
                                      action="{% url 'orders:add-product' %}"
                                      onsubmit="addToCart(event, '{{ product.id }}')">
                                    {% csrf_token %}
                                    <input type="hidden" name="product_id" value="{{ product.id }}">
                                    <div class="text-center mt-8">
                                        <button type="submit"
                                                class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                                            Add to Cart
                                        </button>
                                    </div>
                                </form>
                                <!-- Product content goes here -->
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
    </div>
    <script>
        function addToCart(event, productId) {
            event.preventDefault(); // Prevent the default form submission behavior

            var form = document.getElementById("add-to-cart-form-" + productId);
            var formData = new FormData(form);

            fetch(form.action, {
                method: form.method,
                body: formData,
                headers: {
                    'X-Requested-With': 'XMLHttpRequest'
                }
            })
                .then(response => response.json())
                .then(data => {
                    // Handle the JSON response
                    var message = data.response; // Extract the message from the response
                    displayMessage(message); // Display the message
                })
                .catch(error => {
                    // Handle error here
                    console.error('Error:', error);
                    // Add error message
                    var errorMessage = 'Failed to add product to cart. Please try again.';
                    displayMessage(errorMessage); // Display the error message
                });
        }

        function displayMessage(message) {
            var messagesDiv = document.getElementById("messages");
            // Clear existing messages
            messagesDiv.innerHTML = '';

            var messageElement = document.createElement("div");
            messageElement.classList.add("alert");
            messageElement.textContent = message;
            messagesDiv.appendChild(messageElement);
        }
    </script>

{% endblock %}

products/templates/product.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}{{ product.brand }} {% endblock %}

{% block content %}
    <!-- post_card.html -->
    <div class="w-5/6 mx-auto bg-white rounded-xl shadow-xl overflow-hidden p-4 border border-gray-300 mt-4">
        <div class="text-center">
            <h2 class="text-lg font-bold">{{ product.brand }} / {{ product.name }}</h2>
            <hr class="my-2 w-10/12 mx-auto border-t-2 border-blue-500">
        </div>
        <div class="flex justify-around mt-4">
            <!-- Categories go here -->
            {% for category in product.categories %}
                <div class="category"><a
                        href="{% url 'products:category_products' slug=category.slug pk=category.pk %}">{{ category.category }}</a>
                </div>
            {% endfor %}

            <!-- Add more categories as needed -->
        </div>
        <hr class="w-9/12 mx-auto border-t-2 border-gray-400 mt-4">

        <!-- Images related to the product -->
        <div class="flex justify-around mt-4">
            <!-- Images go here -->
            {% for img in product.images %}
                <div class="w-64 h-64 flex items-center justify-center border rounded-md overflow-hidden transform transition-transform duration-300 hover:scale-105">
                    <img src="{{ img.image.url }}" alt="{{ img.image.url }}" class="object-cover h-full w-full">
                </div>
            {% endfor %}

            <!-- Add more images as needed -->
        </div>
        <!-- Description of the product -->
        <div class="mt-8">
            <h3 class="text-lg font-semibold">Description</h3>
            <p>{{ product.description }}</p>
            <!-- Add more content for the description as needed -->
        </div>

        <!-- Div for capacity and pricing -->
        <div class="flex justify-between w-5/6 mt-4">
            <div class="w-3/4 flex justify-center">
                {% if product.discount_amount %}
                    <div class="flex flex-col justify-center items-center m-4">
                        <div>Final Price</div>
                        <div>{{ product.final_price }}</div>
                    </div>
                {% endif %}
                <div class="flex flex-col justify-center items-center m-4">
                    <div>Price</div>

                    <div {% if product.discount_amount %}
                        style="text-decoration: line-through;" {% endif %}>{{ product.price }}</div>

                </div>
                {% if product.discount_amount %}
                    <div class="flex flex-col justify-center items-center m-4">
                        <div>Discount</div>
                        <div>{{ product.discount_amount }} {{ product.discount_type }}</div>
                    </div>
                {% endif %}
            </div>
            <div class="w-1/4 flex flex-col justify-center items-center">
                <div class="text-center">
                    <div>Capacity</div>
                    <div>{{ product.stock }}</div>
                </div>
            </div>
        </div>

        <!-- Add to Cart button -->
        <form id="add-to-cart-form" method="post" action="{% url 'orders:add-product' %}" onsubmit="addToCart(event)">
            {% csrf_token %}
            <input type="hidden" id="product_id" name="product_id" value="{{ product.product_id }}">
            <div class="text-center mt-8">
                <button type="submit"
                        class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                    Add to Cart
                </button>
            </div>
        </form>

        <script>
            function addToCart(event) {
                event.preventDefault(); // Prevent the default form submission behavior

                var form = document.getElementById("add-to-cart-form");
                var formData = new FormData(form);

                fetch(form.action, {
                    method: form.method,
                    body: formData,
                    headers: {
                        'X-Requested-With': 'XMLHttpRequest'
                    }
                })
                    .then(response => response.json())
                    .then(data => {
                        // Handle the JSON response
                        var message = data.response; // Extract the message from the response
                        displayMessage(message); // Display the message
                    })
                    .catch(error => {
                        // Handle error here
                        console.error('Error:', error);
                        // Add error message
                        var errorMessage = 'Failed to add product to cart. Please try again.';
                        displayMessage(errorMessage); // Display the error message
                    });
            }

            function displayMessage(message) {
                var messagesDiv = document.getElementById("messages");
                // Clear existing messages
                messagesDiv.innerHTML = '';

                var messageElement = document.createElement("div");
                messageElement.classList.add("alert");
                messageElement.textContent = message;
                messagesDiv.appendChild(messageElement);
            }
        </script>
    </div>


{% endblock %}