config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('products.urls')),
    path('', include('customers.urls')),
    path('', include('orders.urls')),
    path('api/', include('orders.api.urls_api')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customers/urls.py
from django.urls import path
from . import views

app_name = 'customers'

urlpatterns = [
    path('edit-profile/', views.EditProfileView.as_view(), name='edit-profile'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('change-password/', views.CustomPasswordChangeView.as_view(), name='change-password'),
    path('new-address/', views.AddNewAddressView.as_view(), name='new-address'),
    path('address/', views.ShowAddressView.as_view(), name='address'),
    path('address/<int:pk>/delete/', views.DeleteAddressView.as_view(), name='delete-address'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'


urlpatterns = [
    path('add-product/', views.AddToOrderItem.as_view(), name='add-product'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('paid-orders/', views.PaidOrdersView.as_view(), name='paid-orders'),
    path('order/<int:pk>/', views.OrderDetailsView.as_view(), name='order-details'),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('products/<slug:slug>/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('', views.HomePageView.as_view(), name='home'),
    path('category/<slug:slug>/<int:pk>/', views.CategoryProductView.as_view(), name='category_products')
]

orders/models.py
from django.core.validators import MinValueValidator
from django.db import models
from core.models import TimeStampMixin, LogicalMixin
from customers.models import Customer, Address
from django.utils import timezone
from django.core.exceptions import ValidationError
from products.models import Product, Price
from products.models import Discount as ProductDiscount
from utils.validators import validate_not_in_past
from django.db.models import UniqueConstraint, Q
from django.utils.translation import gettext_lazy as _


class Order(LogicalMixin, TimeStampMixin):
    customer = models.ForeignKey(Customer,
                                 verbose_name=_("Customer"),
                                 on_delete=models.SET_NULL, null=True,
                                 related_name='orders')
    address = models.ForeignKey(Address, verbose_name=_("Address"),
                                on_delete=models.SET_NULL,
                                null=True, blank=True,
                                related_name='orders')
    is_paid = models.BooleanField(verbose_name=_("Is paid"), default=False)
    paid_time = models.DateTimeField(verbose_name=_("Paid time"), null=True, blank=True)
    discount_code = models.ForeignKey('DiscountCode', verbose_name=_("Discount code"),
                                      null=True, on_delete=models.SET_NULL, blank=True,
                                      related_name='orders')

    def __str__(self):
        return f'{self.id}-{self.customer}'

    def clean(self):
        super().clean()
        if self.address:
            if self.address.customer != self.customer:
                raise ValidationError('Address must be related to this customer')

    class Meta:
        verbose_name = _("Order")
        verbose_name_plural = _("Orders")
        # todo: add constraint(just 1 not paid order)

    def save(self, *args, **kwargs):
        if self.is_paid and not self.paid_time:
            self.paid_time = timezone.now()
        super().save(*args, **kwargs)

    def order_details(self):  # Without Discount Code
        temp = dict()
        temp['owner'] = self.customer.full_name if self.customer.full_name else self.customer.customer.username
        temp['items'] = list()
        for order_item in self.order_items.all():
            temp['items'].append(order_item.order_item_details())

        temp['final_order_subtotal'] = self.calculate_order_total_prices('subtotal')
        temp['final_order_discount'] = self.calculate_order_total_prices('total_discount')
        temp['final_order_price'] = temp['final_order_subtotal'] - temp['final_order_discount']
        return temp

    def paid_order_details(self):
        temp = dict()
        temp['owner'] = self.customer.full_name if self.customer.full_name else self.customer.customer.username
        temp['items'] = list()
        # for order_item in self.order_items.filter(is_deleted=False):
        for order_item in self.order_items.all():
            temp['items'].append(order_item.paid_order_item_detail())
        temp['final_order_subtotal'] = self.calculate_paid_order_total_prices('subtotal')
        temp['final_order_discount'] = self.calculate_paid_order_total_prices('total_discount')
        temp['final_order_price'] = temp['final_order_subtotal'] - temp['final_order_discount']
        return temp

    def calculate_order_total_prices(self, field):
        total_price = 0
        for order_item in self.order_items.all():
            total_price += order_item.order_item_details()[field]
        return total_price

    def calculate_paid_order_total_prices(self, field):
        total_price = 0
        for order_item in self.order_items.all():
            total_price += order_item.paid_order_item_detail()[field]
        return total_price

    def final_price_after_discount_code(self, cart_type: str):
        if cart_type == 'unpaid':
            total_before_discount = self.order_details()['final_order_price']
        else:
            total_before_discount = self.paid_order_details()['final_order_price']

        if self.discount_code:
            if self.discount_code.is_percent_type:
                if (total_before_discount - (total_before_discount * (
                        1 - self.discount_code.amount / 100))) < self.discount_code.max_discount:
                    final_price_after_discount = total_before_discount * (1 - self.discount_code.amount / 100)

                else:
                    final_price_after_discount = total_before_discount - self.discount_code.max_discount

            else:
                if total_before_discount - self.discount_code.amount < 0:
                    final_price_after_discount = 0

                else:
                    final_price_after_discount = total_before_discount - self.discount_code.amount

            return round(final_price_after_discount, 2)
        return round(total_before_discount, 2)

    def calculate_paid_order_total_prices_by_discount_code(self):
        return self.final_price_after_discount_code('paid')

    def calculate_order_total_prices_by_discount_code(self):
        return self.final_price_after_discount_code('unpaid')

    def calculate_order_total_discount_by_discount_code(self):
        return round(
            self.order_details()['final_order_subtotal'] - self.calculate_order_total_prices_by_discount_code(), 2)

    @property
    def invoice_number(self):
        return self.id + 1000


# def validate_address_customer_match(self):
#     if self.address and self.address.customer != self.customer:
#         raise ValidationError("Address does not belong to the customer.")
#
# def clean(self):
#     self.validate_address_customer_match()
#     super().clean()

# class Meta:
#     constraints = [
#         models.CheckConstraint(
#             check=models.Q(address__isnull=True) | models.Q(address__customer=models.F('customer')),
#             name='order_address_customer_match'
#         )
#     ]

# def save(self, *args, **kwargs):
#     print(1)
#     if self.is_paid and not self.paid_time:  # If order is being marked as paid for the first time
#         self.paid_time = timezone.now()
#     elif self.is_paid and self.paid_time:  # If is_paid is already True and being set again
#         raise ValidationError("Order has already been paid.")
#     super().save(*args, **kwargs)


class OrderItem(LogicalMixin, TimeStampMixin):
    order = models.ForeignKey(Order,
                              verbose_name=_("Order"),
                              on_delete=models.SET_NULL, null=True,
                              related_name='order_items')
    product = models.ForeignKey(Product, verbose_name=_("Product"), on_delete=models.SET_NULL, null=True)
    quantity = models.PositiveIntegerField(verbose_name=_("Quantity"), validators=[MinValueValidator(1)])
    product_discount = models.ForeignKey(ProductDiscount,
                                         verbose_name=_("Product discount"),
                                         on_delete=models.SET_NULL, null=True, blank=True,
                                         related_name='order_items')
    price = models.ForeignKey(Price, verbose_name=_("Price"), on_delete=models.CASCADE,
                              null=True, blank=True, related_name='order_items')

    class Meta:
        constraints = [
            UniqueConstraint(
                fields=['order', 'product'],
                condition=Q(is_deleted=False),
                name='in not deleted order item: unique product and order '
            )
        ]
        verbose_name = _("Order Item")
        verbose_name_plural = _("Order Items")

    def clean(self):
        super().clean()
        if self.product_discount and self.product_discount.product != self.product:
            raise ValidationError("Product discount product must be equal to the product.")

    def __str__(self):
        return f'{self.order} - {self.product} - {self.quantity}'

    def item_name(self):
        return f"{self.product.brand}/{self.product.name}"

    def order_item_details(self):
        temp = dict()
        temp['name'] = f"{self.product.brand}/{self.product.name}"
        temp['product_price'] = self.product.prices.first().price
        temp['product_id'] = self.product.id
        temp['discount_unit'] = self.product.prices.first().discount_amount()
        temp['quantity'] = self.quantity
        temp['subtotal'] = temp['quantity'] * temp['product_price']
        temp['total_discount'] = temp['quantity'] * temp['discount_unit']
        temp['total_price'] = temp['subtotal'] - temp['total_discount']
        temp['slug'] = self.product.slug
        return temp

    def paid_order_item_detail(self):
        temp = dict()
        temp['name'] = f"{self.product.brand}/{self.product.name}"
        temp['product_price'] = self.price.price
        temp['product_id'] = self.product.id
        if self.product_discount:
            if self.product_discount.is_percent_type:
                temp['discount_unit'] = round(
                    self.price.price - (self.price.price * (1 - self.product_discount.amount / 100)), 2)
            else:
                temp['discount_unit'] = round(self.product_discount.amount, 2)
        else:
            temp['discount_unit'] = 0
        temp['quantity'] = self.quantity
        temp['subtotal'] = temp['quantity'] * temp['product_price']
        temp['total_discount'] = temp['quantity'] * temp['discount_unit']
        temp['total_price'] = temp['subtotal'] - temp['total_discount']
        temp['slug'] = self.product.slug
        return temp


class DiscountCode(LogicalMixin, TimeStampMixin):
    code = models.CharField(verbose_name=_("Code"), max_length=15)
    is_percent_type = models.BooleanField(verbose_name=_("Is percent type"),
                                          default=True)
    amount = models.DecimalField(verbose_name=_("Amount"),
                                 max_digits=15, decimal_places=2,

orders/forms.py
from django import forms
from orders.models import DiscountCode


class CheckoutForm(forms.Form):
    address = forms.ChoiceField(label='Select an address', choices=[], required=True)
    discount_code = forms.CharField(label='Enter Discount Code', max_length=100, required=False)

    def clean_discount_code(self):
        discount_code = self.cleaned_data.get('discount_code')
        if discount_code:
            if not DiscountCode.objects.filter(code=discount_code, is_deleted=False, is_used=False).exists():
                raise forms.ValidationError("Invalid discount code.")
        return discount_code

orders/templates/orders/checkout-cart.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %} CheckOut {% endblock %}
{% block content %}


    <div class="min-h-screen bg-gray-100 p-4 mt-4">
        <div class="max-w-6xl mx-auto shadow-md rounded-lg overflow-hidden">
            <div class="bg-gray-800 flex justify-between text-white p-4 text-lg font-bold">
                <span>{{ order.owner }}</span> <span class="text-gray-300">Hamid Online Shop </span></div>

            <div class="p-4">


                <table class="w-full border border-gray-400 my-2 bg-gray-200">
                    <thead>
                    <tr class="text-gray-500 font-bold ">
                        <th class="p-2 text-center">Product Name</th>
                        <th class="p-2 text-center">Price/Unit</th>
                        <th class="p-2 text-center">Discount/Unit</th>
                        <th class=" text-center pl-9">Quantity</th>
                        <th class="p-2 text-center">Subtotal</th>
                        <th class="p-2 text-center">Discount</th>
                        <th class="p-2 text-center">Total Price</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in order.items %}
                        <tr class="row_{{ item.product_id }}">
                            <td class="p-2 text-center">
                                <a href="{% url 'products:product_detail' slug=item.slug pk=item.product_id %}"
                                   style="text-decoration: none;"
                                   onmouseover="style.textDecoration='underline';"
                                   onmouseout="style.textDecoration='none';">
                                    {{ item.name }}
                                </a>
                            </td>
                            <td id="product_price_{{ item.product_id }}"
                                class="p-2 text-center">{{ item.product_price }}</td>
                            <td id="product_discount_{{ item.product_id }}" class="p-2 text-center">
                                {% if item.discount_unit %}
                                    {{ item.discount_unit }} {% else %}
                                    0.00 {% endif %}
                            </td>
                            <td class="p-2 text-center flex items-center justify-center">


                                <span id="product_quantity_{{ item.product_id }}"
                                      class="px-4 ml-8">{{ item.quantity }}</span>

                            </td>

                            <td id="product_subtotal_{{ item.product_id }}"
                                class="p-2 text-center">{{ item.subtotal }}</td>
                            <td id="product_total_discount_{{ item.product_id }}"
                                class="p-2 text-center">{{ item.total_discount }}</td>
                            <td id="product_total_price_{{ item.product_id }}"
                                class="p-2 text-center">{{ item.total_price }}</td>
                        </tr>
                    {% endfor %}
                    <tr>
                        <td class="p-2 text-center"></td>
                        <td class="p-2 text-center"></td>
                        <td class="p-2 text-center"></td>
                        <td class="p-2 text-center font-bold pl-10 italic">Total:</td>
                        <td id="final_order_subtotal" class="p-2 text-center font-bold"
                            style="text-decoration: underline;">{{ order.final_order_subtotal }}</td>
                        <td id="final_order_discount" class="p-2 text-center font-bold"
                            style="text-decoration: underline;">{{ order.final_order_discount }}</td>
                        <td id="final_order_price" class="p-2 text-center font-bold"
                            style="{% if not has_discount %} text-decoration: underline; color: red {% else %} text-decoration: line-through ; {% endif %} ">{{ order.final_order_price }}</td>
                    </tr>

                    <tr {% if not entered_discountCode %} style="display: none" {% endif %}>
                        <td class="p-2 text-center"></td>
                        <td class="p-2 text-center"></td>
                        <td class="p-2 text-center"></td>
                        <td class="p-2 text-center font-bold pl-10 italic">Final Amount:</td>
                        <td id="final_order_subtotal" class="p-2 text-center font-bold"
                            style="text-decoration: underline;">{{ order.final_order_price }}</td>
                        <td id="final_order_discount" class="p-2 text-center font-bold"
                            style="text-decoration: underline; color: #fc5318">- {{ discount_of_code }}</td>
                        <td id="final_order_price" class="p-2 text-center font-bold "
                            style="text-decoration: underline; color: red">{{ final_order_price_after_discount_code }}</td>
                    </tr>

                    </tbody>
                </table>
                <hr class="my-2 w-10/12 mx-auto border-t-2 border-blue-500 mt-6">

                <form method="post">
                    {% csrf_token %}
                    <div>
                        <div class="flex justify-start items-center p-4">
                            <label for="id_address" class="mr-4 font-bold">Select an address:</label>
                            <div class="relative flex pl-6">
                                <select id="id_address" name="address"
                                        class="block w-full px-4 py-2 rounded-md border border-gray-300 focus:border-blue-500 focus:ring focus:ring-blue-500 focus:ring-opacity-50 appearance-none bg-white hover:border-blue-500"
                                        style="width: 300px;">
                                    <option {% if not selected_address %} value="{{ addresses.first.id }}" {% else %}
                                                                          value="{{ selected_address.id }}" {% endif %}>
                                        {% if not selected_address %} {{ addresses.first }} {% else %}
                                            {{ selected_address }} {% endif %}
                                    </option>
                                    {% if not selected_address %}
                                        {% for address in addresses|slice:"1:" %}
                                            <option value="{{ address.id }}">{{ address }}</option>
                                        {% endfor %}
                                    {% else %}
                                        {% for address in addresses %}
                                            {% if address != selected_address %}
                                                <option value="{{ address.id }}">{{ address }}</option>
                                            {% endif %}
                                        {% endfor %}
                                    {% endif %}
                                </select>
                                <div class="absolute inset-y-0 right-0 flex items-center pr-3 pointer-events-none">
                                    <svg class="h-5 w-5 text-gray-400" fill="none" viewBox="0 0 24 24"
                                         stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                              d="M19 9l-7 7-7-7"></path>
                                    </svg>
                                </div>
                            </div>
                            <a href="{% url 'customers:new-address' %}" id="addNewAddress"
                               class="text-white font-bold py-2 px-8 mx-4 rounded mr-2 flex items-center justify-center mb-4 mt-4"
                               style="width: 250px; background-color: #4ade80; transition: background-color 0.3s;"
                               onmouseover="this.style.backgroundColor='#65a30d';"
                               onmouseout="this.style.backgroundColor='#4ade80';">
                                Add New Address
                            </a>
                        </div>

                        {% if form.address.errors %}
                            <div class="text-red-500">
                                {{ form.address.errors }}
                            </div>
                        {% endif %}

                        <div class="flex justify-start items-center p-4">
                            <label for="discountCode" class="mr-4 font-bold">Enter Discount Code:</label>
                            <div class="relative flex">
                                <input id="discountCode" type="text" name="discount_code" placeholder="Discount Code"
                                        {% if entered_discountCode %} value="{{ entered_discountCode }} {% endif %}"
                                       class="form-input mt-1 block w-full px-4 py-2 rounded-md border border-gray-300 focus:outline-none focus:border-blue-500 focus:ring focus:ring-blue-500 focus:ring-opacity-50 bg-white hover:border-blue-500"
                                       style="width: 300px;">
                                <button id="applyDiscountButton" type="submit"
                                        class="text-white font-bold py-2 px-8 ml-4 rounded mr-2 flex items-center justify-center"
                                        style="width: 250px;margin-top: 3px; background-color: #4ade80; transition: background-color 0.3s;"
                                        onmouseover="this.style.backgroundColor='#65a30d';"
                                        onmouseout="this.style.backgroundColor='#4ade80';">
                                    Apply
                                </button>
                            </div>
                        </div>

                        {% if form.discount_code.errors %}
                            <div class="text-red-500">
                                {{ form.discount_code.errors }}
                            </div>
                        {% endif %}

                    </div>

                    <div class="flex justify-end p-4">
                        <a href="{% url 'orders:cart' %}"
                           class="mx-2 bg-yellow-500 text-white px-4 py-2 rounded shadow-sm hover:bg-yellow-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-400">
                            Edit Cart
                        </a>
                        <button id="payButton" type="submit" name="payment"
                                class="mx-2 bg-blue-500 text-white px-4 py-2 rounded shadow-sm hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-400">
                            Pay Now
                        </button>
                    </div>
                </form>


            </div>
        </div>
    </div>

    <script>
        document.getElementById("addNewAddress").addEventListener("click", function () {
            var currentUrl = "http://127.0.0.1:8000/en/checkout/";
            if (currentUrl.indexOf('login') === -1 && currentUrl.indexOf('signup') === -1 && currentUrl.indexOf('activation') === -1) {
                // Set the cookie
                document.cookie = "next_url_checkout=" + currentUrl + ";path=/";
            }
        });
    </script>

{% endblock %}

orders/templates/orders/paid-carts.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %} Paid Orders {% endblock %}
{% block content %}
    <div class="flex flex-col justify-center items-center mx-auto w-10/12 mt-4 ">
        <!-- Personal Information Part -->
        <div class="flex flex-col justify-center items-center border border-gray-400 p-4 rounded m-1 mb-4 bg-gray-100"
             style="width: 95%">

            <h2 class="text-xl font-semibold mb-4">Paid Baskets</h2>
            <hr class="w-full border-gray-300 mb-4">

            {% for order in orders %}
                <a href="{% url 'orders:order-details' pk=order.id|add:1000 %}" class="w-full flex justify-center">
                    <div id="ttt"
                         class="flex justify-around items-center border border-gray-400 p-4 rounded m-1 bg-blue-100 my-4"
                         style="width: 95%;">
                        <div style="width: 24%;">
                            <span class="font-bold">✔ Invoice number: </span>
                            <span class="italic" style="text-decoration: underline;">{{ order.invoice_number }}</span>
                        </div>
                        <div style="width: 22%;">
                            <span class="font-bold">Amount: </span>
                            <span class="italic"
                                  style="text-decoration: underline;">{{ order.calculate_paid_order_total_prices_by_discount_code}}</span>
                        </div>
                        <div style="width: 22%;">
                            <span class="font-bold">Discount: </span>
                            <span class="italic"
                                  style="text-decoration: underline;">{{ order.calculate_order_total_discount_by_discount_code }}</span>
                        </div>
                        <div style="width: 30%;">
                            <span class="font-bold">Date:</span>
                            <span class="italic" style="text-decoration: underline;">{{ order.paid_time }} </span>
                        </div>
                    </div>
                </a>
            {% endfor %}

        </div>
    </div>
{% endblock %}