config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('products.urls')),
    path('', include('customers.urls')),
    path('', include('orders.urls')),
    path('api/', include('orders.api.urls_api')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customers/urls.py
from django.urls import path
from . import views

app_name = 'customers'

urlpatterns = [
    path('edit-profile/', views.EditProfileView.as_view(), name='edit-profile'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('change-password/', views.CustomPasswordChangeView.as_view(), name='change-password'),
    path('new-address/', views.AddNewAddressView.as_view(), name='new-address'),
    path('address/', views.ShowAddressView.as_view(), name='address'),
    path('address/<int:pk>/delete/', views.DeleteAddressView.as_view(), name='delete-address'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'


urlpatterns = [
    path('add-product/', views.AddToOrderItem.as_view(), name='add-product'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('paid-orders/', views.PaidOrdersView.as_view(), name='paid-orders'),
    path('order/<int:pk>/', views.OrderDetailsView.as_view(), name='order-details'),
]

customers/models.py
from django.core.validators import RegexValidator
from django.db import models
from django.db.models import UniqueConstraint, Q
from accounts.models import User
from core.models import TimeStampMixin, LogicalMixin
from django.utils.translation import gettext_lazy as _


class Customer(LogicalMixin, TimeStampMixin):
    customer = models.ForeignKey(User, verbose_name=_("Customer"), on_delete=models.SET_NULL, null=True,
                                 related_name='customers')
    phone_number = models.CharField(verbose_name=_("Phone number"), max_length=11,
                                    null=True, blank=True)  # todo: add validator
    customer_type = models.SmallIntegerField(verbose_name=_("Customer type"), default=5)
    full_name = models.CharField(verbose_name=_("Full name"), max_length=100, null=True, blank=True)

    class Meta:
        constraints = [
            UniqueConstraint(
                fields=['customer'],
                condition=Q(is_deleted=False),
                name='unique_not_deleted_customer'
            )
        ]
        verbose_name = _("Customer")
        verbose_name_plural = _("Customers")

    def __str__(self):
        return f"{self.customer.username}"


class Address(LogicalMixin, TimeStampMixin):
    updated_at = None
    is_active = None

    customer = models.ForeignKey(Customer,
                                 verbose_name=_("Customer"),
                                 on_delete=models.CASCADE,
                                 related_name='addresses')
    province = models.CharField(verbose_name=_("Province"), max_length=100)
    city = models.CharField(verbose_name=_("City"), max_length=100)
    details = models.TextField(verbose_name=_("Details"), )
    post_code = models.CharField(verbose_name=_("Post code"), max_length=10, validators=[
        RegexValidator(
            regex='^\d{10}$',
            message='Code must be exactly 10 digits long'
        )
    ])
    has_paid_order = models.BooleanField(verbose_name=_("Used in Order"), default=False)

    def __str__(self):
        return f"{self.province} - {self.city} - {self.post_code}"

    def delete(self):
        if self.has_paid_order:
            super().delete()
        else:
            super().hard_delete()

    class Meta:
        verbose_name = _("Address")
        verbose_name_plural = _("Addresses")

customers/forms.py
from django import forms
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.hashers import check_password

from customers.models import Address


class EditProfileForm(forms.Form):
    name = forms.CharField(label='name', widget=forms.TextInput(), required=False)
    phone = forms.CharField(label='phone', widget=forms.TextInput(), required=False)
    email = forms.EmailField(label='phone', widget=forms.TextInput())
    username = forms.CharField(label='phone', widget=forms.TextInput())


class CustomPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput())
    new_password1 = forms.CharField(widget=forms.PasswordInput())
    new_password2 = forms.CharField(widget=forms.PasswordInput())

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        if not check_password(old_password, self.user.password):
            raise forms.ValidationError("Your old password was entered incorrectly. Please enter it again.")
        return old_password

    def clean_password1(self):
        return self.cleaned_data.get('new_password1')

    def clean_password2(self):
        return self.cleaned_data.get('new_password2')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["new_password1"])
        if commit:
            user.save()
        return user


class NewAddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ('province', 'city', 'details', 'post_code')

customers/views.py
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import TemplateView, CreateView, View
from .forms import EditProfileForm, CustomPasswordChangeForm, NewAddressForm
from .models import Customer, Address
from accounts.models import User
from django.db import IntegrityError
from accounts.tasks import otp_sender
from django.core.cache import cache
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy
from core.mixin import NavbarMixin, LoginRequiredMixin
from django.contrib.auth.models import AnonymousUser
from .permissions import DeleteAddressPermission
from orders.models import Order


class EditProfileView(NavbarMixin, TemplateView):
    template_name = 'customers/editprofile.html'

    def dispatch(self, request, *args, **kwargs):
        self.user = request.user
        # Login Required
        if isinstance(request.user, AnonymousUser) or not request.user.is_authenticated:
            return redirect('accounts:login')

        self.customer = Customer.objects.get(customer=self.user)
        # Initialize fields of form
        email = self.user.email
        username = self.user.username
        phone = Customer.objects.get(customer=self.user).phone_number
        name = Customer.objects.get(customer=self.user).full_name
        temp = dict()
        temp['name'] = name
        temp['email'] = email
        temp['phone'] = phone
        temp['username'] = username
        self.temp = temp

        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['initial'] = self.temp
        return context

    def get(self, request, *args, **kwargs):
        form = EditProfileForm()
        context = self.get_context_data()
        context['form'] = form
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        form = EditProfileForm(request.POST)
        if form.is_valid():
            # change Full name and Phone number
            self.customer.full_name = form.cleaned_data['name']
            self.customer.phone_number = form.cleaned_data['phone']
            self.customer.save()

            new_username = form.cleaned_data['username']
            new_email = form.cleaned_data['email']

            # Change username field
            try:
                self.user.username = new_username
                self.user.save()
            except IntegrityError:
                form.add_error('username', "Username already exists")
                return self.render_to_response({'form': form, 'initial': self.temp})

            # Change email field
            if new_email != self.user.email:
                check_email = User.objects.filter(email=new_email).first()
                if check_email:
                    form.add_error('email', "Email already exists!")
                    return self.render_to_response({'form': form, 'initial': self.temp})
                else:

                    # Redirect to Verification
                    otp_sender.delay(email=new_email, username=new_username)
                    cache.set(f"{self.user.pk}", new_email, timeout=300)
                    return redirect('accounts:activation', pk=self.user.pk)
            return redirect('customers:profile')
        return self.render_to_response({'form': form, 'initial': self.temp})


class ProfileView(LoginRequiredMixin, NavbarMixin, TemplateView):
    template_name = 'customers/profile.html'
    context_object_name = 'profile'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['email'] = self.request.user.email
        context['username'] = self.request.user.username
        context['name'] = Customer.objects.get(customer=self.request.user).full_name
        context['phone'] = Customer.objects.get(customer=self.request.user).phone_number
        context['paid_orders_count'] = Order.objects.filter(customer__customer=self.request.user, is_paid=True).count()

        return context


class CustomPasswordChangeView(LoginRequiredMixin, NavbarMixin, PasswordChangeView):
    form_class = CustomPasswordChangeForm
    template_name = 'customers/change-password.html'
    success_url = reverse_lazy('customers:profile')


class AddNewAddressView(LoginRequiredMixin, NavbarMixin, CreateView):
    template_name = 'customers/new-address.html'
    form_class = NewAddressForm

    def get_success_url(self):
        next_url = self.request.COOKIES.get('next_url_checkout')
        if next_url:
            return reverse_lazy('orders:checkout')
        return reverse_lazy('customers:address')

    def form_valid(self, form):
        customer = Customer.objects.get(customer=self.request.user)
        form.instance.customer = customer

        return super().form_valid(form)


class ShowAddressView(LoginRequiredMixin, NavbarMixin, TemplateView):
    template_name = 'customers/addresses.html'

    def get_context_data(self, **kwargs):
        customer = Customer.objects.get(customer=self.request.user)
        context = super().get_context_data(**kwargs)
        context['addresses'] = customer.addresses.all().order_by('-created_at')
        return context


class DeleteAddressView(DeleteAddressPermission, NavbarMixin, View):

    def get(self, request, *args, **kwargs):
        address = get_object_or_404(Address, pk=self.kwargs['pk'])
        address.delete()
        return redirect('customers:address')

customers/templates/customers/addresses.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %} Profile {% endblock %}
{% block content %}
    <div class="flex flex-col justify-center items-center mx-auto w-10/12 mt-4 ">
        <!-- Personal Information Part -->
        <div class="flex flex-col justify-center items-center border border-gray-400 p-4 rounded m-1 mb-4 bg-gray-100"
             style="width: 95%">

            <h2 class="text-xl font-semibold mb-4"> Addresses </h2>
            <hr class="w-full border-gray-300 mb-4">
            <a href="{% url 'customers:new-address' %}"
               class="text-white font-bold py-2 px-8 mx-4 rounded mr-2 flex items-center justify-center mb-4"
               style="width: 250px; background-color: #4ade80; transition: background-color 0.3s;"
               onmouseover="this.style.backgroundColor='#65a30d';"
               onmouseout="this.style.backgroundColor='#4ade80';">
                Add New Address
            </a>
            <hr class="my-2 w-10/12 mx-auto border-t-2 border-blue-500 mb-4">

            {% for address in addresses %}

                <!-- Personal Information Part -->
                <div class="flex flex-col justify-center items-center border border-gray-400 p-4 rounded m-1 mb-4 bg-blue-100 my-4"
                     style="width: 95%">


                    <!-- top -->
                    <div class="flex items-center justify-center flex">

                        <div class="flex w-1/3 mx-2  p-4 rounded m-1  mx-10" style="width: 270px;">
                            <div class=" flex mt-2">
                                <span class="px-2 font-bold">  Province:</span>
                                <span class="px-2 italic"
                                      style="text-decoration: underline;"> {{ address.province }}</span>
                            </div>
                        </div>

                        <div class="flex w-1/3 mx-2  p-4 rounded m-1  mx-10" style="width: 270px;">
                            <div class=" flex mt-2 ">
                                <span class="px-2 font-bold">  City:</span>
                                <span class="px-2 italic"
                                      style="text-decoration: underline;"> {{ address.city }}</span>
                            </div>
                        </div>


                        <div class="flex w-1/3 mx-2  p-4 rounded m-1  mx-10" style="width: 270px;">
                            <div class=" flex mt-2 ">
                                <span class="px-2 font-bold">  Post Code:</span>
                                <span class="px-2 italic"
                                      style="text-decoration: underline;"> {{ address.post_code }}</span>
                            </div>
                        </div>
                    </div>
                    <!-- /top -->

                    <div class="flex items-center justify-center flex-col">

                        <div class="flex w-1/3 mx-2  p-4 rounded m-1  mx-10" style="width: 340px;">
                            <div class=" flex mt-2">
                                <span class="px-2 font-bold">  Details:</span>
                                <span class="px-2 italic"
                                      style="text-decoration: underline;"> {{ address.details }}</span>
                            </div>
                        </div>

                        <div class="flex justify-between mt-4">
                            <a href="{% url 'customers:delete-address' pk=address.pk %}"
                               class="text-white font-bold py-2 px-8 mx-4 rounded mr-2 flex items-center justify-center"
                               style="width: 250px; background-color: #ea580c; transition: background-color 0.3s;"
                               onmouseover="this.style.backgroundColor='#b91c1c';"
                               onmouseout="this.style.backgroundColor='#ea580c';">
                                Delete Address
                            </a>

                        </div>
                    </div>


                </div>


            {% endfor %}
        </div>
    </div>
{% endblock %}

customers/templates/customers/change-password.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %} Change Password {% endblock %}
{% block content %}
<div class="flex justify-center items-center h-screen" style="background-image: url({% static 'BackgroundImages/bgos2.jpg' %}); background-size: cover; background-repeat: no-repeat; background-position: center; background-attachment: fixed;">
    <div class="bg-gradient-to-r from-blue-400 via-blue-300 to-gray p-8 rounded-lg shadow-md w-full max-w-md">
        <h2 class="text-2xl mb-6 text-center">Change Password</h2>
        <form method="post" action="" class="space-y-4" novalidate>
            {% csrf_token %}
            <div class="mb-4">
                <label for="old_password" class="block text-gray-700">Old Password</label>
                <input id="old_password" type="password" name="old_password" placeholder="Old Password" class="form-input mt-1 block w-full bg-green-100 border border-green-300 rounded-md focus:outline-none focus:border-green-500">
                {% if form.old_password.errors %}
                    <p class="text-red-500 text-sm mt-1">{{ form.old_password.errors }}</p>
                {% endif %}
            </div>

            <div class="mb-4">
                <label for="new_password1" class="block text-gray-700">New Password</label>
                <input id="new_password1" type="password" name="new_password1" placeholder="New Password" class="form-input mt-1 block w-full bg-green-100 border border-green-300 rounded-md focus:outline-none focus:border-green-500">
                {% if form.new_password1.errors %}
                    <p class="text-red-500 text-sm mt-1">{{ form.new_password1.errors }}</p>
                {% endif %}
            </div>
            <div class="mb-4">
                <label for="new_password2" class="block text-gray-700">Confirm New Password</label>
                <input id="new_password2" type="password" name="new_password2" placeholder="Confirm New Password" class="form-input mt-1 block w-full bg-green-100 border border-green-300 rounded-md focus:outline-none focus:border-green-500">
                {% if form.new_password2.errors %}
                    <p class="text-red-500 text-sm mt-1">{{ form.new_password2.errors }}</p>
                {% endif %}
            </div>
            <div class="flex items-center justify-between">
                <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600">Change Password</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

customers/templates/customers/editprofile.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %} Edit Profile {% endblock %}
{% block content %}
    <div class="flex justify-center items-center h-screen" style="background-image: url({% static 'BackgroundImages/bgos2.jpg' %}); background-size: cover; background-repeat: no-repeat; background-position: center; background-attachment: fixed;">
        <div class="bg-gradient-to-r from-blue-400 via-blue-300 to-gray p-8 rounded-lg shadow-md w-full max-w-md">
            <h2 class="text-2xl mb-6 text-center">Edit Information</h2>
            <form method="post" class="space-y-4" novalidate>
                {% csrf_token %}

                <div class="mb-4">
                    <label for="email" class="block text-gray-700">Email</label>
                    <input id="email" type="email" name="email" value="{{ initial.email }}"
                           placeholder="Username"
                           class="form-input mt-1 block w-full bg-green-100 border border-green-300 rounded-md focus:outline-none focus:border-green-500">
                    {% if form.email.errors %}
                        <p class="text-red-500 text-sm mt-1">{{ form.email.errors }}</p>
                    {% endif %}
                </div>

                <div class="mb-4">
                    <label for="username" class="block text-gray-700">Username</label>
                    <input id="username" type="text" name="username" value="{{ initial.username }}"
                           placeholder="Username"
                           class="form-input mt-1 block w-full bg-green-100 border border-green-300 rounded-md focus:outline-none focus:border-green-500">
                    {% if form.username.errors %}
                        <p class="text-red-500 text-sm mt-1">{{ form.username.errors }}</p>
                    {% endif %}
                </div>

                <div class="mb-4">
                    <label for="name" class="block text-gray-700">Full name</label>
                    <input id="name" type="text" name="name" value="{% if initial.name %}{{ initial.name }} {% endif %}"
                           placeholder="Full name"
                           class="form-input mt-1 block w-full bg-green-100 border border-green-300 rounded-md focus:outline-none focus:border-green-500">
                    {% if form.name.errors %}
                        <p class="text-red-500 text-sm mt-1">{{ form.name.errors }}</p>
                    {% endif %}
                </div>

                <div class="mb-4">
                    <label for="phone" class="block text-gray-700">Phone number</label>
                    <input id="phone" type="text" name="phone"
                           value="{% if initial.phone %}{{ initial.phone }} {% endif %}" placeholder="Phone number"
                           class="form-input mt-1 block w-full bg-green-100 border border-green-300 rounded-md focus:outline-none focus:border-green-500">
                    {% if form.phone.errors %}
                        <p class="text-red-500 text-sm mt-1">{{ form.phone.errors }}</p>
                    {% endif %}
                </div>

                <div class="flex items-center justify-between">
                    <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600">Edit
                    </button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

customers/templates/customers/new-address.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %} New Address {% endblock %}
{% block content %}

    <div class="flex justify-center items-center h-screen"
         style="background-image: url({% static 'BackgroundImages/bgos2.jpg' %}); background-size: cover; background-repeat: no-repeat; background-position: center; background-attachment: fixed;">
        <div class="bg-gradient-to-r from-blue-400 via-blue-300 to-gray p-8 rounded-lg shadow-md w-full max-w-md">
            <h2 class="text-2xl mb-6 text-center text-black">Add New Address</h2>
            <form method="post" class="space-y-4" novalidate>
                {% csrf_token %}
                {% for field in form %}
                    <div class="mb-4">
                        <label for="{{ field.id_for_label }}" class="block text-gray-700">{{ field.label }}</label>
                        <input id="{{ field.id_for_label }}" type="{{ field.field.widget.input_type }}"
                               name="{{ field.name }}" placeholder="{{ field.label }}"
                               class="form-input mt-1 block w-full bg-green-100 border border-green-300 rounded-md focus:outline-none focus:border-green-500">
                        {% if field.errors %}
                            <p class="text-red-500 mt-1">{{ field.errors }}</p>
                        {% endif %}
                    </div>
                {% endfor %}
                <div class="flex items-center justify-between">
                    <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600">Add
                        Address
                    </button>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

customers/templates/customers/profile.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %} Profile {% endblock %}
{% block content %}
    <div class="flex flex-col justify-center items-center mx-auto w-10/12 mt-4 ">
        <!-- Personal Information Part -->
        <div class="flex flex-col justify-center items-center border border-gray-400 p-4 rounded m-1 mb-4 bg-gray-100"
             style="width: 95%">

            <h2 class="text-xl font-semibold mb-4">Personal Information</h2>
            <hr class="w-full border-gray-300 mb-4">

            <!-- top -->
            <div class="flex items-center justify-evenly flex-wrap">

                <div class="flex w-1/3 mx-2  p-4 rounded m-1  mx-10" style="width: 400px;">
                    <div class=" flex mt-2">
                        <span class="px-2 font-bold">  Name:</span>
                        <span class="px-2 italic" style="text-decoration: underline;"> {{ name }}</span>
                    </div>
                </div>

                <div class="flex w-1/3 mx-2  p-4 rounded m-1  mx-10" style="width: 400px;">
                    <div class=" flex mt-2 ">
                        <span class="px-2 font-bold">  Phone number:</span>
                        <span class="px-2 italic" style="text-decoration: underline;"> {{ phone }}</span>
                    </div>
                </div>

            </div>
            <!-- /top -->

            <!-- bot -->
            <div class="flex items-center justify-evenly flex-wrap">

                <div class="flex w-1/3 mx-2  p-4 rounded m-1  mx-10" style="width: 400px;">
                    <div class=" flex mt-2">
                        <span class="px-2 font-bold">  Email:</span>
                        <span class="px-2 italic" style="text-decoration: underline;"> {{ email }}</span>
                    </div>
                </div>

                <div class="flex w-1/3 mx-2  p-4 rounded m-1  mx-10" style="width: 400px;">
                    <div class=" flex mt-2 ">
                        <span class="px-2 font-bold">  Username:</span>
                        <span class="px-2 italic" style="text-decoration: underline;"> {{ username }}</span>
                    </div>
                </div>

            </div>
            <!-- bot -->


            <!-- Links -->
            <div class="flex justify-between mt-4">

                <a href="{% url 'customers:edit-profile' %}"
                   class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-8 mx-4 rounded mr-2 flex items-center justify-center"
                   style="width: 250px;">
                    Edit Information
                </a>

                <a href="{% url 'customers:change-password' %}"
                   class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-8 mx-4 rounded mr-2 flex items-center justify-center"
                   style="width: 250px;">
                    Change Password
                </a>

            </div>

            <div class="flex justify-between mt-4">

                <a href="{% url 'customers:address' %}"
                   class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-8 mx-4 rounded mr-2 flex items-center justify-center"
                   style="width: 250px;">
                    Address
                </a>

            </div>
            <!-- /Links -->
        </div>
        <!-- /Personal Information Part -->


        <!-- Order Part -->
        <div class="flex flex-col justify-center items-center border border-gray-400 p-4 rounded m-1 mb-4 bg-gray-100"
             style="width: 95%">

            <h2 class="text-xl font-semibold mb-4">My Orders</h2>
            <hr class="w-full border-gray-300 mb-4">

            <div class="flex items-center justify-evenly flex-wrap">

                <a href="{% url 'orders:cart' %}">
                    <div class="flex w-1/3 mx-2 p-4 rounded m-1  mx-10" style="width: 200px;">
                        <img src="{% static 'Profile/status-processing.svg' %}" alt="processing" class="mr-4">
                        <div class=" flex flex-col mt-2">
                            <span> Current </span>
                            <span> order </span>
                        </div>
                    </div>
                </a>

                <a href="{% url 'orders:paid-orders' %}">
                    <div class="flex w-1/3 mx-2 p-4 rounded m-1  mx-10" style="width: 200px;">
                        <img src="{% static 'Profile/status-delivered.svg' %}" alt="processing" class="mr-4">
                        <div class=" flex flex-col mt-2 ">
                            <span> {{ paid_orders_count }} Orders</span>
                            <span> delivered</span>
                        </div>
                    </div>
                </a>

                <a href="#">
                    <div class="flex w-1/3 mx-2 p-4 rounded m-1  mx-10" style="width: 200px;">
                        <img src="{% static 'Profile/status-returned.svg' %}" alt="processing" class="mr-4">
                        <div class=" flex flex-col mt-2 ">
                            <span> 0 Orders</span>
                            <span> returned</span>
                        </div>
                    </div>
                </a>

            </div>
        </div>
        <!-- /Order Part -->


    </div>
{% endblock %}